allowBuilds:
  '@parcel/watcher': false
  esbuild: false

minimumReleaseAge: 0
minimumReleaseAgeStrict: false
patchedDependencies:
  vitepress-plugin-llms@1.14.0: patches/vitepress-plugin-llms@1.14.0.patch
